# Generated by Django 2.1 on 2018-09-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180907_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='decription',
            new_name='description',
        ),
    ]
